import unittest
from enum import Enum

from src.game.overcooked.config import CrampedRoomOvercookedConfig
from src.game.overcooked.overcooked import OvercookedGame


class TestOvercookedGame(unittest.TestCase):
    def test_init_print(self):
        game_cfg = CrampedRoomOvercookedConfig()
        game = OvercookedGame(game_cfg)
        game.render()
        game.step((0, 2))
        game.render()
        game.step((3, 5))
        game.render()

    def test_put_in_pot(self):
        game_cfg = CrampedRoomOvercookedConfig()
        game = OvercookedGame(game_cfg)
        game.render()
        game.step((0, 2))
        game.render()
        game.step((3, 5))
        game.render()
        game.step((5, 3))
        game.render()
        reward, _, _ = game.step((4, 0))
        print(reward)
        game.render()
        reward, _, _ = game.step((4, 5))
        print(reward)
        game.render()

    def test_cooking(self):
        game_cfg = CrampedRoomOvercookedConfig()
        game = OvercookedGame(game_cfg)
        game.step((0, 2))
        game.step((3, 5))
        game.step((5, 3))
        game.step((4, 0))
        game.step((4, 5))
        game.render()
        game.step((2, 2))
        game.render()
        game.step((0, 5))
        game.render()
        game.step((5, 4))
        game.render()
        game.step((3, 3))
        game.render()
        game.step((1, 0))
        game.render()
        game.step((5, 5))
        game.render()
        game.step((5, 5))
        game.render()
        for _ in range(20):
            game.step((4, 4))
            game.render()
        print(game.get_cum_rewards())

    def test_delivery(self):
        game_cfg = CrampedRoomOvercookedConfig()
        game = OvercookedGame(game_cfg)
        game.step((0, 2))
        game.step((3, 5))
        game.step((5, 3))
        game.step((4, 0))
        game.step((4, 5))
        game.step((2, 2))
        game.step((0, 5))
        game.step((5, 4))
        game.step((3, 3))
        game.step((1, 0))
        game.step((4, 5))
        game.step((4, 5))
        game.render()
        reward, _, _ = game.step((5, 4))
        game.render()
        print(reward)
        for _ in range(20):
            game.step((4, 4))
        game.render()
        game.step((2, 2))
        game.render()
        game.step((0, 1))
        game.render()
        game.step((5, 3))
        game.render()
        game.step((2, 4))
        game.render()
        game.step((1, 4))
        game.render()
        print(game.get_cum_rewards())
        game.step((5, 4))
        game.render()
        print(game.get_cum_rewards())

    def test_copy(self):
        game_cfg = CrampedRoomOvercookedConfig()
        game = OvercookedGame(game_cfg)
        game2 = OvercookedGame.get_copy(game)
        game.render()
        game2.render()
        print('##############################')
        game.step((2, 2))
        game.render()
        game2.render()
        print('##############################')
        game.reset()
        game.render()
        game2.render()
        print('##############################')


