__module__: src.depth.depth_parallel
__name__: DepthSearchConfig
data:
  device_str: cpu
  draw_prevention: true
  game_cfg:
    __module__: src.game.battlesnake.battlesnake_conf
    __name__: BattleSnakeConfig
    data:
      all_actions_legal: false
      constrictor: false
      ec:
        __module__: src.game.battlesnake.battlesnake_enc
        __name__: VanillaBattleSnakeEncodingConfig
        data:
          centered: true
          compress_enemies: false
          fixed_food_spawn_chance: -1
          flatten: false
          include_area_control: false
          include_board: true
          include_current_food: true
          include_distance_map: true
          include_food_distance: false
          include_hazards: false
          include_next_food: false
          include_num_food_on_board: false
          include_number_of_turns: false
          include_snake_body: true
          include_snake_body_as_one_hot: true
          include_snake_head: true
          include_snake_health: true
          include_snake_length: true
          include_snake_tail: true
          include_tail_distance: false
          single_temperature_input: true
          temperature_input: false
      food_spawn_chance: 15
      h: 7
      hazard_damage: 14
      init_food_pos: null
      init_hazards: null
      init_snake_health: null
      init_snake_len:
      - 3
      - 3
      init_snake_pos: null
      init_snakes_alive: null
      init_turns_played: 0
      max_snake_health: null
      min_food: 1
      num_actions: 4
      num_players: 2
      reward_cfg:
        __module__: src.game.battlesnake.battlesnake_rewards
        __name__: StandardBattleSnakeRewardConfig
        data:
          living_reward: 0.0
          terminal_reward: 1.0
      royale: false
      shrink_n_turns: 25
      w: 7
      wrapped: false
  include_ja_values: true
  include_obs: true
  max_available_actions: 3
  min_available_actions: 2
  num_procs: 2
  num_samples: 3
  restrict_cpu: false
  save_path: /home/mahlau/nobackup/albatross/a_data/debug_data
  search_specs:
    __dict__:
      duct:
        __module__: src.misc.serialization
        __name__: TupleWrapper
        data:
          data:
          - __module__: src.search.config
            __name__: MCTSConfig
            data:
              backup_func_cfg:
                __module__: src.search.config
                __name__: StandardBackupConfig
                data: {}
              discount: 0.99
              eval_func_cfg:
                __module__: src.search.config
                __name__: AreaControlEvalConfig
                data:
                  health_threshold: 1.0
                  utility_norm:
                    __module__: src.game.values
                    __name__: UtilityNorm
                    value: NONE
              expansion_depth: 0
              extract_func_cfg:
                __module__: src.search.config
                __name__: StandardExtractConfig
                data: {}
              optimize_fully_explored: false
              sel_func_cfg:
                __module__: src.search.config
                __name__: DecoupledUCTSelectionConfig
                data:
                  exp_bonus: 1.414
              use_hot_start: false
          - null
          - 100
          - 5
  seed: 42
  step_iterations: null
  step_search: duct
  step_temperature: 5
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}